<?php
namespace frontend\models;

use yii\db\ActiveRecord;

class Cart extends ActiveRecord{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}